# -*- coding: utf-8 -*-
"""UsingTuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Z_PS6_iZ-We2S3SaA7OtQkaVRtGn5Xp
"""

# Access and Print

student_records = [
    (101, "Alice Smith", 85, "Computer Science"),
    (102, "Bob Johnson", 92, "Engineering"),
    (103, "Charlie Brown", 78, "Computer Science"),
    (104, "Diana Prince", 95, "Arts"),
    (105, "Ethan Hunt", 88, "Engineering"),
    (106, "Fiona Glenanne", 75, "Computer Science"),
]

for record in student_records:
  print("Name : ", record[1], "Grade : ", record[2])

def get_students_by_major(records, major_name):
  filtered_list = [item for item in records if item[3] == major_name]
  return filtered_list

get_students_by_major(student_records, "Computer Science")

def calculate_average_grade(records):
  sum = 0
  average = 0
  for record in records:
    sum = sum + record[2]
  average = sum / len(records)
  return average

average_grade_for_all = calculate_average_grade(student_records)
print("Average grade for all students : " , average_grade_for_all)

computer_science_students = get_students_by_major(student_records, "Computer Science")

average_grade_for_major = calculate_average_grade(computer_science_students)
print("Average grade for Computer Science students : " , average_grade_for_major)